version: '3'
services:
    boulder:
        # To minimize fetching this should be the same version used below
        image: letsencrypt/boulder-tools-go${TRAVIS_GO_VERSION:-1.15}:2020-08-12
        environment:
            - FAKE_DNS=10.77.77.77
            - BOULDER_CONFIG_DIR=labca/config
            - GOFLAGS=-mod=vendor
            # This is required so Python doesn't throw an error when printing
            # non-ASCII to stdout.
            - PYTHONIOENCODING=utf-8
            # These are variables you can set to affect what tests get run or
            # how they are run. Including them here with no value means they are
            # passed through from the environment.
            - RUN
            - INT_FILTER
            - RACE
        volumes:
          - .:/go/src/github.com/letsencrypt/boulder:cached
          - /home/labca/boulder_labca:/go/src/github.com/letsencrypt/boulder/labca
          - ./.gocache:/root/.cache/go-build:cached
        networks:
          bluenet:
            ipv4_address: 10.77.77.77
            aliases:
              - sa1.boulder
              - ca1.boulder
              - ra1.boulder
              - va1.boulder
              - publisher1.boulder
              - ocsp-updater.boulder
              - admin-revoker.boulder
              - nonce1.boulder
          rednet:
            ipv4_address: 10.88.88.88
            aliases:
              - sa2.boulder
              - ca2.boulder
              - ra2.boulder
              - va2.boulder
              - publisher2.boulder
              - nonce2.boulder
        # Use sd-test-srv as a backup to Docker's embedded DNS server
        # (https://docs.docker.com/config/containers/container-networking/#dns-services).
        # If there's a name Docker's DNS server doesn't know about, it will
        # forward the query to this IP (running sd-test-srv). We have
        # special logic there that will return multiple IP addresses for
        # service names.
        dns: 10.77.77.77
        ports:
          - 4000:4000 # ACME
          - 4001:4001 # ACMEv2
          - 4002:4002 # OCSP
          - 4003:4003 # OCSP
          - 4430:4430 # ACME via HTTPS
          - 4431:4431 # ACMEv2 via HTTPS
          - 8055:8055 # dns-test-srv updates
        depends_on:
          - bmysql
        entrypoint: labca/entrypoint.sh
        working_dir: /go/src/github.com/letsencrypt/boulder
        logging:
          driver: "json-file"
          options:
            max-size: "500k"
            max-file: "5"
        restart: always
    bmysql:
        image: mariadb:10.5
        volumes:
          - dbdata:/var/lib/mysql
        networks:
          bluenet:
            aliases:
              - boulder-mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        # Send slow queries to a table so we can check for them in the
        # integration tests. For now we ignore queries not using indexes,
        # because that seems to trigger based on the optimizer's choice to not
        # use an index for certain queries, particularly when tables are still
        # small.
        command: mysqld --bind-address=0.0.0.0 --slow-query-log --log-output=TABLE --log-queries-not-using-indexes=ON
        logging:
          driver: "json-file"
          options:
            max-size: "500k"
            max-file: "5"
        restart: always
    labca:
        image: letsencrypt/boulder-tools-go${TRAVIS_GO_VERSION:-1.15}:2020-08-12
        networks:
          - bluenet
        volumes:
          - /home/labca/admin:/go/src/labca
          - ./.gocache:/root/.cache/go-build
          - /var/www/html:/wwwstatic
          - .:/boulder
          - /home/labca/boulder_labca:/boulder/labca
        ports:
          - 3000:3000
        depends_on:
          - bmysql
        working_dir: /go/src/labca
        command: ./setup.sh
        logging:
          driver: "json-file"
          options:
            max-size: "500k"
            max-file: "5"
        restart: always
    
    labca-nginx:
      image: nginx:latest
      ports:
        80:80
        443:443
      volumes:
        - ./www:/usr/share/nginx/html
        - ./nginx.conf:/etc/nginx/sites-enabled/default
        - ./ssl:/etc/nginx/ssl/
      

volumes:
    dbdata:

networks:
  bluenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.77.77.0/24
  rednet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.88.88.0/24
